//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        public int IDAbonent { get; set; }
        public string SurName { get; set; }
        public string FirstName { get; set; }
        public string Patron { get; set; }
        public string Passport { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> IDTarif { get; set; }
    
        public virtual Tarif Tarif { get; set; }
    }
}
